# Generated by Django 4.1.4 on 2023-01-05 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_info',
            new_name='bio',
        ),
    ]
