# Generated by Django 4.1.4 on 2023-01-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_alter_comment_post'),
        ('post', '0003_rename_likes_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment',
            field=models.ManyToManyField(related_name='Post_Comment', to='comment.comment'),
        ),
    ]
